name: CI Pipeline - Calculadora

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm install  

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2

      - name: Verificar vulnerabilidade
        run: npm audit --audit-level=high

  quality:
    runs-on: ubuntu-latest
    needs: security
  
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Run Coverage
        run: npm run test -- --coverage

  build:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Rodar build
        run: echo "Build realizado com sucesso"

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test
  
  deploy: 
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: protection
    
    steps:
      - name: Simular deploy
        run: echo "Deploy realizado com sucesso"